#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 6379, host: 6379

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision "shell", path: "https://git.io/v65JW", name: "Firewalld"
  config.vm.provision "shell", path: "https://git.io/v65J0", name: "ImageMagick"
  config.vm.provision "shell", path: "https://git.io/v65UA", name: "Redis"
  config.vm.provision "shell", path: "https://git.io/v65Uj", name: "RVM", privileged: false
  config.vm.provision "shell", path: "https://git.io/v65Ui", name: "Node.js", privileged: false
end
