#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1","virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 3001, host: 3001

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision "shell", inline: <<-SHELL
    echo "Updating System"
    apt-get update  > /dev/null 2>&1
    apt-get install build-essential  > /dev/null 2>&1
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    hash node 2>/dev/null || {
      echo "Installing Node.js"
      cd /home/vagrant/app
      sudo apt-get install curl -y > /dev/null 2>&1
      curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash > /dev/null 2>&1
      echo "source /home/vagrant/.nvm/nvm.sh" >> /home/vagrant/.profile
      source /home/vagrant/.profile
      nvm install 5.0  > /dev/null 2>&1
      nvm use 5.0  > /dev/null 2>&1
      nvm alias default 5.0  > /dev/null 2>&1
    }
  SHELL

end
