#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vm.customize ["guestproperty", "set", :id, "--timesync-threshold", 5000]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 3306, host: 3307

  config.vm.synced_folder "app", "/var/www/html", create: true

  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/default", name: "Default"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/imagemagick", name: "ImageMagick"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/mariadb", name: "MariaDB"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/php7", name: "PHP7"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/apache", name: "Apache"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/ruby", name: "Ruby", privileged: false
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/nodejs", name: "Node.js", privileged: false
end