#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection
 
Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, '--nictype1','virtio']
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 3306, host: 3307

  config.vm.synced_folder "app", "/var/www", :create => true

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe "apt"
    chef.add_recipe "apache2"
    chef.add_recipe "php"
    chef.add_recipe "mysql::server"
    chef.add_recipe "apache2::mod_php5"
    chef.add_recipe "apache2::mod_rewrite"
    chef.add_recipe "php::module_curl"
    chef.add_recipe "php::module_mysql"

    chef.json.merge!({
      :apache2 => {
        :default_site_enabled => true
      },
      :mysql => {
        :server_root_password => "vagrant",
        :server_repl_password => "vagrant",
        :server_debian_password => "vagrant",
        :allow_remote_root => true
      }
    })
  end
  config.vm.provision :shell, :inline => "sudo a2ensite default"
  config.vm.provision :shell, :inline => "sudo service apache2 restart"

end