# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.5'
  config.ssh.insert_key = false

  scripts = 'https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/'

  config.vm.provider :virtualbox do |vm|
    vm.customize ['modifyvm', :id, '--memory', 1536]
    vm.customize ['modifyvm', :id, '--cpus', '2']
    vm.customize ['modifyvm', :id, '--ioapic', 'on']
    vm.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vm.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
    vm.customize ['guestproperty', 'set', :id, '--timesync-threshold', 5000]
  end

  config.vm.network :private_network, type: 'dhcp'
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true

  config.vm.synced_folder 'app', '/home/vagrant/app', create: true, type: 'nfs',
    mount_options: ['rw', 'vers=3', 'tcp'],
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async']

  config.vm.provision 'shell', path: 'default', name: 'Default'
  config.vm.provision 'shell', path: "#{scripts}imagemagick", name: 'ImageMagick'
  config.vm.provision 'shell', path: "#{scripts}mariadb", name: 'MariaDB'
  config.vm.provision 'shell', path: "#{scripts}php7", name: 'PHP7'
  config.vm.provision 'shell', path: "#{scripts}apache", name: 'Apache'
  config.vm.provision 'shell', path: "#{scripts}ruby", name: 'Ruby', privileged: false
  config.vm.provision 'shell', path: "#{scripts}nodejs", name: 'Node.js', privileged: false
end
