#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'yum'
cookbook 'build-essential'
cookbook 'selinux'
cookbook 'iptables'
cookbook 'openssh'
cookbook 'openssl'
cookbook 'apache2', '~> 3.0.1'
cookbook 'php'
cookbook 'mysql', '= 5.6.1'
