#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "mullen/centos7-64"
  config.vm.hostname = "DMREN"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, '--nictype1','virtio']
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 3306, host: 3307

  config.vm.synced_folder "app", "/opt/python/current/app", :create => true

  config.vm.provision :chef_solo do |chef|
    chef.custom_config_path = "Vagrantfile.chef"
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe "yum"
    chef.add_recipe "build-essential"
    chef.add_recipe "mysql::server"

    chef.json.merge!({
      :mysql => {
        :server_root_password => "vagrant",
        :server_repl_password => "vagrant",
        :server_debian_password => "vagrant",
        :allow_remote_root => true
      }
    })
  end

  config.vm.provision :shell, :inline => "sudo systemctl mask firewalld"
  config.vm.provision :shell, :inline => "sudo systemctl stop firewalld"
  config.vm.provision :shell, :inline => "sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/epel-release.rpm"
  config.vm.provision :shell, :inline => "sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm"
  config.vm.provision :shell, :inline => "sudo yum install python-pip MySQL-python libpng-devel git mysql gcc-c++ mailcap automake mysql-devel python-devel libpng-devel libcurl-devel libxml2-devel openssl-devel libstdc++-devel -y"
  config.vm.provision :shell, :inline => "sudo pip install -r /opt/python/current/app/requirements.txt"
  config.vm.provision :shell, :inline => "sudo ln -s /opt/python/current/app/ /home/vagrant/app"
end
