#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mullen/centos7-64"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.network :forwarded_port, guest: 8228, host: 8228
  config.vm.network :forwarded_port, guest: 4000, host: 4000

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision :chef_solo do |chef|
    chef.custom_config_path = "Vagrantfile.chef"
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "nodejs"
    chef.add_recipe "mongodb::10gen_repo"
    chef.add_recipe "mongodb::default"

    chef.json.merge!({
      nodejs: {
        npm_packages: [
          { name: "grunt-cli" },
          { name: "grunt" },
          { name: "grunt-bower" }
        ]
      }
    })
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo systemctl mask firewalld
    sudo systemctl stop firewalld
  SHELL

end
