#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'nodejs'

cookbook 'rvm'

cookbook 'git', :git => 'https://github.com/fnichol/chef-git.git'

cookbook 'mariadb', :git => 'https://github.com/joerocklin/chef-mariadb.git'