#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection
 
Vagrant.configure("2") do |config|
  config.vm.box = "mullen/vagrant-trusty64"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, '--nictype1','virtio']
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 3306, host: 3307

  config.vm.synced_folder "app", "/home/vagrant/app", :create => true

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "rvm::vagrant"
    chef.add_recipe "rvm::system"
    chef.add_recipe "git"
    chef.add_recipe "nodejs"
    chef.add_recipe "mariadb::client"
    chef.add_recipe "mariadb::server"

    chef.json.merge!({
      :rvm => {
        :default_ruby => 'ruby-2.1.2',
        :global_gems => [
          { "name" => "bundler" },
          { "name" => "rails" },
        ]
      },
      :mariadb => {
        :server_root_password => "vagrant",
        :server_repl_password => "vagrant",
        :server_debian_password => "vagrant",
        :client => {
          :packages => ["libmariadbclient-dev"]
        },
      },
    })

  end
end