#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.hostname = "APPNAME"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 27017, host: 27017
  config.vm.network :forwarded_port, guest: 28017, host: 28017

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision "shell", inline: "curl -fsS https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/firewalld.sh | bash"
  config.vm.provision "shell", inline: "curl -fsS https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/imagemagick.sh | bash"
  config.vm.provision "shell", inline: "curl -fsS https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/mongodb.sh | bash"
  config.vm.provision "shell", privileged: false, inline: "curl -fsS https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/rvm.sh | bash"
  config.vm.provision "shell", privileged: false, inline: "curl -fsS https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/node.sh | bash"

end
