# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.5'
  config.ssh.insert_key = false

  scripts = 'https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/'

  config.vm.provider :virtualbox do |vm|
    vm.customize ['modifyvm', :id, '--memory', 1536]
    vm.customize ['modifyvm', :id, '--cpus', '2']
    vm.customize ['modifyvm', :id, '--ioapic', 'on']
    vm.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vm.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
    vm.customize ['guestproperty', 'set', :id, '/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold', 10000 ]
  end

  config.vm.network 'private_network', type: 'dhcp'

  config.vm.provision 'shell', path: "#{scripts}default", name: 'Default'
  config.vm.provision 'shell', path: "#{scripts}postgresql", name: 'PostgreSQL'
  config.vm.provision 'shell', path: "#{scripts}erlang", name: 'Erlang'
  config.vm.provision 'shell', path: "#{scripts}elixir", name: 'Elixir'
  config.vm.provision 'shell', path: "#{scripts}phoenix", name: 'Phoenix', privileged: false
  config.vm.provision 'shell', path: "#{scripts}nodejs", name: 'Node.js', privileged: false
  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    /sbin/ifconfig enp0s8 | grep 'inet ' | cut -d: -f2 | awk '{print 'IP ADDRESSS: ' $2}'
  SHELL
end
