#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.hostname = "APPNAME"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 3306, host: 3307

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
  SHELL


  config.vm.provision "shell", inline: <<-SHELL
    if ! type docker > /dev/null; then
      yum update -y
      sudo apt-get install curl
      systemctl mask firewalld
      systemctl stop firewalld
      rpm -Uvh https://mirror.webtatic.com/yum/el7/epel-release.rpm
      rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
      curl -fsSL https://get.docker.com/ | sh
      usermod -aG docker vagrant
      chkconfig docker on
      service docker start
    fi
  SHELL
end



