#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection
 
Vagrant.configure("2") do |config|
  config.vm.box = "raringringtail"
  config.vm.box_url = "http://goo.gl/Y4aRr"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
      vm.customize ["modifyvm", :id, "--memory", 1536]
      vm.customize ["modifyvm", :id, "--cpus", "2"]
      vm.customize ["modifyvm", :id, "--ioapic", "on"]
      vm.customize ["modifyvm", :id, '--nictype1','virtio']
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 27017, host: 27017
  config.vm.network :forwarded_port, guest: 28017, host: 28017

  config.vm.synced_folder "app", "/home/vagrant/app", :create => true

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "rvm::vagrant"
    chef.add_recipe "rvm::system"
    chef.add_recipe "git"
    chef.add_recipe "nodejs"
    chef.add_recipe "mongodb::10gen_repo"
    chef.add_recipe "mongodb::default"

    chef.json.merge!({
      :rvm => {
        :default_ruby => 'ruby-2.1.2',
        :global_gems => [
          { "name" => "bundler" },
          { "name" => "rails" }
        ]
      },
    })

  end
end