#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mullen/vagrant-trusty64"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, '--nictype1','virtio']
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 9000, host: 9001

  config.vm.synced_folder "app", "/home/vagrant/app", :create => true

  config.vm.provision :chef_solo do |chef|
    chef.custom_config_path = "Vagrantfile.chef"
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "rvm::vagrant"
    chef.add_recipe "rvm::system"
    chef.add_recipe "nodejs"

    chef.json.merge!({
      :rvm => {
        :default_ruby => 'ruby-2.2.1',
        :global_gems => [
          { "name" => "bundler" },
          { "name" => "rails" },
          { "name" => "scss" },
          { "name" => "compass" }
        ]
      },
      :nodejs => {
        :version => "0.12.7"
      }
    })
  end
  config.vm.provision :shell, :inline => "npm install -g grunt-cli grunt grunt-bower yo bower generator-webapp"
  config.vm.provision :shell, :inline => "cd /home/vagrant/app && npm install"
end
