#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1","virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 3001, host: 3001

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision "shell", path: "https://git.io/v65JW", name: "Firewalld"
  config.vm.provision "shell", path: "https://git.io/v65Uj", name: "RVM", privileged: false
  config.vm.provision "shell", path: "https://git.io/v65Ui", name: "Node.js", privileged: false

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    hash rails 2>/dev/null || {
      gem install sass compass
    }

    hash grunt 2>/dev/null || {
      npm install -g grunt grunt-cli grunt-bower yo bower generator-webapp phantomjs-prebuilt gulp-cli  > /dev/null 2>&1
    }
  SHELL
end
