#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'nvm', :git => 'https://github.com/HuzuTech/chef-nvm'
cookbook 'git', :git => 'https://github.com/fnichol/chef-git.git'
cookbook 'mongodb', :git => 'https://github.com/edelight/chef-mongodb.git'