#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'nodejs'
cookbook 'mongodb', :git => 'https://github.com/edelight/chef-mongodb.git'
