#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'nodejs', :git => 'https://github.com/mdxp/nodejs-cookbook.git'
cookbook 'rvm'
