#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["guestproperty", "set", :id, "--timesync-threshold", 5000]
  end

  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "app", "/home/vagrant/app", create: true, type: "nfs", nfs_udp: false

  config.vm.provision "shell", path: "https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/default.sh", name: "Default"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/postgresql-md5.sh", name: "PostgreSQL"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/erlang.sh", name: "Erlang"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/elixir.sh", name: "Elixir"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/phoenix.sh", name: "Phoenix", privileged: false
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/Mullen/vagrant/master/scripts/node.sh", name: "Node.js", privileged: false
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    /sbin/ifconfig enp0s8 | grep 'inet ' | cut -d: -f2 | awk '{print "IP ADDRESSS: " $2}'
  SHELL
end
