#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.hostname = "APPNAME"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 3306, host: 3307

  config.vm.synced_folder "app", "/opt/python/current/app", create: true


  config.vm.provision "shell", inline: <<-SHELL
    echo "Updating System"
    sudo apt-get update  > /dev/null 2>&1
    sudo apt-get install build-essential  > /dev/null 2>&1

    sudo systemctl mask firewalld
    sudo systemctl stop firewalld


    hash mysql 2>/dev/null || {
      echo "Installing MySQL"
      yum install httpd mariadb-server mariadb -y
      systemctl enable mariadb.service
      systemctl start mariadb.service
      mysql -uroot -e 'use mysql;UPDATE user SET password=PASSWORD("vagrant") WHERE User="root";GRANT ALL PRIVILEGES ON *.* TO "root"@"%" IDENTIFIED BY "vagrant" WITH GRANT OPTION;FLUSH PRIVILEGES;'    
      echo "bind-address=0.0.0.0" >> /etc/my.cnf
      systemctl restart mariadb.service
    }

    hash pip 2>/dev/null || {
      sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/epel-release.rpm
      sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
      sudo yum install python-pip MySQL-python libpng-devel git mysql gcc-c++ mailcap automake mysql-devel python-devel libpng-devel libcurl-devel libxml2-devel openssl-devel libstdc++-devel -y
      sudo pip install -r /opt/python/current/app/requirements.txt
      sudo ln -s /opt/python/current/app/ /home/vagrant/app
    }
  SHELL
end
