# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.5'
  config.ssh.insert_key = false

  scripts = 'https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/centos/'

  config.vm.provider :virtualbox do |vm|
    vm.customize ['modifyvm', :id, '--memory', 1536]
    vm.customize ['modifyvm', :id, '--cpus', '2']
    vm.customize ['modifyvm', :id, '--ioapic', 'on']
    vm.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vm.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
    vm.customize ['guestproperty', 'set', :id, '--timesync-threshold', 5000]
  end

  config.vm.network :private_network, type: 'dhcp'
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.vm.provision 'shell', path: "#{scripts}default", name: 'Default'
  config.vm.provision 'shell', path: "#{scripts}crystal", name: 'Crystal'
end
