#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 3306, host: 3307

  config.vm.synced_folder "app", "/home/vagrant/app", create: true


  config.vm.provision "shell", inline: <<-SHELL
    echo "Updating System"
    systemctl mask firewalld
    systemctl stop firewalld

    hash convert 2>/dev/null || {
      echo "Installing Imagemagick"
      yum install ImageMagick -y
    }

    hash mysql 2>/dev/null || {
      echo "Installing MySQL"
      yum install httpd mariadb-server mariadb -y
      systemctl enable mariadb.service
      systemctl start mariadb.service
      mysql -uroot -e 'use mysql;UPDATE user SET password=PASSWORD("vagrant") WHERE User="root";GRANT ALL PRIVILEGES ON *.* TO "root"@"%" IDENTIFIED BY "vagrant" WITH GRANT OPTION;FLUSH PRIVILEGES;'    
      echo "bind-address=0.0.0.0" >> /etc/my.cnf
      systemctl restart mariadb.service
    }
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    hash ruby 2>/dev/null || {
      echo "Installing RVM & Ruby"
      sudo apt-get install curl -y > /dev/null 2>&1
      gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3  > /dev/null 2>&1
      curl -sSL https://get.rvm.io | bash -s stable --gems=bundler,sass,rails,compass  > /dev/null 2>&1
    }

    hash node 2>/dev/null || {
      echo "Installing Node.js"
      cd /home/vagrant/app
      sudo apt-get install curl -y > /dev/null 2>&1
      curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash > /dev/null 2>&1
      echo "source /home/vagrant/.nvm/nvm.sh" >> /home/vagrant/.profile
      source /home/vagrant/.profile
      nvm install 5.0  > /dev/null 2>&1
      nvm use 5.0  > /dev/null 2>&1
      nvm alias default 5.0  > /dev/null 2>&1
    }
  SHELL
end
