#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.hostname = "APPNAME"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 5432, host: 55432

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision "shell", inline: <<-SHELL
    hash convert 2>/dev/null || {
      echo "Installing Imagemagick"
      yum install -y ImageMagick-devel ImageMagick > /dev/null 2>&1
    }

    hash psql 2>/dev/null || {
      echo "Installing PostgreSQL"
      rpm -ivh http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm > /dev/null 2>&1
      yum install -y postgresql95 postgresql95-server postgresql95-libs postgresql95-contrib postgresql95-devel postgresql-devel > /dev/null 2>&1
      rm -rf /var/lib/pgsql/9.5/data > /dev/null 2>&1
      /usr/pgsql-9.5/bin/postgresql95-setup initdb   > /dev/null 2>&1
      systemctl start postgresql-9.5 > /dev/null 2>&1
      systemctl enable postgresql-9.5 > /dev/null 2>&1
      chkconfig postgresql-9.5 on > /dev/null 2>&1
      sudo -u postgres psql 2>/dev/null -c "alter user postgres with password 'vagrant'" > /dev/null 2>&1
      sudo -u postgres createuser -s vagrant > /dev/null 2>&1
      echo "host all all 0.0.0.0/0 trust" >> /var/lib/pgsql/9.5/data/pg_hba.conf
      echo "listen_addresses = '*'" >> /var/lib/pgsql/9.5/data/postgresql.conf
      systemctl restart postgresql-9.5 > /dev/null 2>&1
    }
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    hash ruby 2>/dev/null || {
      echo "Installing RVM & Ruby"
      gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3  > /dev/null 2>&1
      curl -sSL https://get.rvm.io | bash -s stable --gems=bundler  > /dev/null 2>&1
    }
    
    hash node 2>/dev/null || {
      echo "Installing Node.js"
      curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash  > /dev/null 2>&1
      echo "source /home/vagrant/.nvm/nvm.sh" >> /home/vagrant/.profile
      source /home/vagrant/.profile
      nvm install 5.0  > /dev/null 2>&1
      nvm use 5.0  > /dev/null 2>&1
      nvm alias default 5.0  > /dev/null 2>&1
    }
  SHELL
end
