#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#^syntax detection

Vagrant.configure("2") do |config|
  config.vm.box = "mullen/vagrant-trusty64"
  config.vm.hostname = "APPNAME"

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 5432, host: 55432

  config.vm.synced_folder "app", "/home/vagrant/app", create: true


  config.vm.provision "shell", inline: <<-SHELL
    if ! type convert > /dev/null; then
      echo "Installing Imagemagick"
      sudo apt-get update  > /dev/null 2>&1
      sudo apt-get install build-essential imagemagick libmagickwand-dev -y > /dev/null 2>&1
    fi

    if ! type psql > /dev/null; then
      echo "Installing PosgreSQL"
      sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
      sudo apt-get update > /dev/null 2>&1
      sudo apt-get install postgresql postgresql-contrib libpq-dev -y > /dev/null 2>&1
      sudo -u postgres createuser -s vagrant > /dev/null 2>&1
      echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/9.5/main/pg_hba.conf
      echo "listen_addresses = '*'" >> /etc/postgresql/9.5/main/postgresql.conf
      sudo service postgresql restart > /dev/null 2>&1
    fi
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    if ! type node > /dev/null; then
      echo "Installing Node.js"
      cd /home/vagrant/app
      curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash > /dev/null 2>&1
      echo "source /home/vagrant/.nvm/nvm.sh" >> /home/vagrant/.profile
      source /home/vagrant/.profile
      nvm install 5.0  > /dev/null 2>&1
      nvm use 5.0  > /dev/null 2>&1
      nvm alias default 5.0  > /dev/null 2>&1
    fi

    if ! type rvm > /dev/null; then
      echo "Installing RVM & Ruby"
      gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 > /dev/null 2>&1
      curl -sSL https://get.rvm.io | bash -s stable --gems=bundler,rails > /dev/null 2>&1
    fi

  SHELL
end