#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do | vm |
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vm.customize ["guestproperty", "set", :id, "--timesync-threshold", 5000]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 5432, host: 55432

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant/master/scripts/default.sh", name: "Default"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant/master/scripts/imagemagick.sh", name: "ImageMagick"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant/master/scripts/postgresql.sh", name: "PostgreSQL"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant/master/scripts/ruby.sh", name: "Ruby", privileged: false
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/stfnhh/vagrant/master/scripts/nodejs.sh", name: "Node.js", privileged: false
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    hash yarn 2>/dev/null || {
      npm install yarn -g > /dev/null 2>&1
    }
    hash rails 2>/dev/null || {
      gem install rails > /dev/null 2>&1
    }
  SHELL
end
