# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-8"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vm|
    vm.customize ["modifyvm", :id, "--memory", 1536]
    vm.customize ["modifyvm", :id, "--cpus", "2"]
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
    vm.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    vm.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end

  config.vm.synced_folder "app", "/home/vagrant/app", create: true

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 5432, host: 5432

  repo = "https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master"
  config.vm.provision "shell", path: "#{repo}/initialization", name: "Initialization"
  config.vm.provision "shell", path: "#{repo}/postgresql", name: "PostgreSQL"
  config.vm.provision "shell", path: "#{repo}/ruby", name: "Ruby", privileged: false
  config.vm.provision "shell", path: "#{repo}/nodejs", name: "Node.js", privileged: false
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    hash yarn 2>/dev/null || {
      npm install yarn -g > /dev/null 2>&1
    }
    hash rails 2>/dev/null || {
      gem install rails > /dev/null 2>&1
    }
  SHELL
end
